### ISSUE TITLE
stellar sdk uses dependency with lgpl licence.

### ISSUE THREAD

**Issue by lishay1989** [matinkaboli/stellar-sdk#4]
Hey @matinkaboli ,
First of all, I would like to thank you for a great crate, it helped me a lot to work with Stellar.

I have noticed that the crate depends on `nacl v0.5.3`, licensed as LGPL 3.0.
From my understanding, it contradicts Stellar-SDK's Apache-2.0 license.

I am not a licensed expert, please advise.

P.S. Our product uses [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) for license checks.

**Comment by amovah** [comment]
Hi, thanks for mentioning this issue.
 I'm not expert at license too, do you think changing repo license can solve this issue or not? something like MIT?

**Comment by lishay1989** [comment]
Hi, I think the best solution is to use crate with "mit"/"apache-2.0" license
that will replace "nacl" which has "LGPL" license. 
so there will be no issues with the license because I don't know if the fact that we are using "LGPL" crate makes this crate "LGPL"

for now, I uploaded pr that makes "nacl" a default feature in our repo.
so users that don't want this feature will be able to use this crate with "default-features = false".
and then they will not have license issues. if they don't need this feature.

this will not affect current users that use this crate as is.

thanks!

**Comment by amovah** [comment]
#5 merged. thanks @lishay1989
