### ISSUE TITLE
stellar sdk doesn't expose error codes

### ISSUE THREAD

**Issue by yotamam** [matinkaboli/stellar-sdk#7]
Hey guys.

Thank you for your support with resolving a previous licensing issue.
We are now facing a new issue when we want to resolve our error handling.
Unfortunately, at the moment there is no way to determine what kind of error the node has returned, since the error code is private and non accessible.

I've opened a PR for a fix suggestion, which just exposes the values so the user can choose how to handle each type of error.
https://github.com/matinkaboli/stellar-sdk/pull/6

I'd be glad if any of you can look at it and merge it or suggest anything different.

**Comment by amovah** [comment]
sorry for delay, forget to take a look. merged.
